import type { Metadata } from "next";
import { Podkova } from "next/font/google";
import "./globals.css";

const podkova = Podkova({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
  variable: "--font-podkova",
});

export const metadata: Metadata = {
  title: "Invest In My Growth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${podkova.variable} font-podkova`}>{children}</body>
    </html>
  );
}
